### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aaroncrespo** [RLovelett/node-sourcekit#4]
Looking at writing typings. Best practice is to basically provide a 1:1 mapping on a file/definition basis
`index.js` -> `index.d.ts`

Looks like we are mapping 1:1 sourcekit to this library which makes sense, but I'm not 100% sure what `SourceKit.cursorinfo` does is it just the swift structure function around a cursor?

**Comment by RLovelett** [comment]
I tried to document what the function does [here](https://github.com/RLovelett/node-sourcekit#cursor-info). Is that sufficient or do you need more information?

**Comment by RLovelett** [comment]
Another thing that occurs to me. Perhaps we should be writing, [what is effectively a `Promise` interface](https://github.com/RLovelett/node-sourcekit/blob/master/lib/node-sourcekit.js), directly in Typescript.

Would that make things any easier?

**Comment by aaroncrespo** [comment]
for #2 makes sense, for #1, I'm so accustomed to languages that have inline documentation as part of their practices, I guess I assumed that would be how node modules are written. Looking around, looks like I was wrong.
