### ISSUE TITLE
TypeScript declaration for the public interface

### ISSUE THREAD

**Issue by RLovelett** [RLovelett/node-sourcekit#8]
In order for [vscode-swift](https://github.com/RLovelett/vscode-swift) to be able to consume this dependency we need TypeScript declarations.

Not sure how to make these.

(I think @aaroncrespo is working on this?)

**Comment by aaroncrespo** [comment]
Yeah, I think the approach most take is making a new repo:
`typed-node-suorcekit` (theres a yo generator for it). Initially this is separate while being worked on, but I think eventually it gets merged into the @types org and managed via @typings

**Comment by RLovelett** [comment]
If we do need a 3rd repo perhaps we should migrate these repost to an organization.

**Comment by aaroncrespo** [comment]
I'm trying to figure out testing but so far cursor info looks something like. I'm not sure if `Promise` translates directly like that?

``` ts
declare interface SourceKitOption {
    sourcefile: File,
    offset: Number,
    compilerargs: any[]
}

declare interface SourceKit {
    // TODO define some result types
    cursorinfo(options: SourceKitOption): (resolve: any, reject: any) => void
}

export = SourceKit;
```

**Comment by aaroncrespo** [comment]
compiler args might also  be improved at least to `string[]`

**Comment by RLovelett** [comment]
I _think_ it is supposed to be 

``` typescript
cursorinfo(options: SourceKitOption): Promise<IYetToBeDeifined>;
```

But making it a true `Promise` has some drawbacks in that it must be run on an ES6 compliant Node. Which limits the Node to very recent versions.

**Comment by RLovelett** [comment]
This is what I've been using to test locally:

``` typescript
declare module "node-sourcekit" {

    export interface ICursorOption {
        sourcefile: string,
        offset: number,
        compilerargs: string[]
    }

    export interface ICursorInfo {
        'key.kind': string,
        'key.name': string,
        'key.usr': string,
        'key.filepath': string,
        'key.offset': number,
        'key.length': number,
        'key.typename': string
        'key.annotated_decl': string
        'key.fully_annotated_decl': string
        'key.typeusr': string
    }

    export function cursorinfo(options: ICursorOption): Promise<ICursorInfo>
}
```

Which enables me to do:

``` typescript
import * as SourceKit from 'node-sourcekit';

let obj: SourceKit.ICursorOption = {
    sourcefile: '/home/ryan/Source/node-sourcekit/test/fixtures/example.swift',
    offset: 487,
    compilerargs: [
        '/home/ryan/Source/node-sourcekit/test/fixtures/example.swift'
    ]
};

SourceKit.cursorinfo(obj).then((info) => {
    console.log(info['key.name']);
});
```

**Comment by aaroncrespo** [comment]
Yeah this is better than a separate repo, if you have a release out I'd reach out to the typings people and see what they think, since these are pre bundled we might not need to be added to the registry.
